---
name: "Terraform Checks"
description: "Perform common Terraform checks"

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: "INFO: Ascertain Terraform Version"
      shell: bash
      run: terraform --version

    - name: "INFO: Linting Terraform Files"
      shell: bash
      run: |
        cd infrastructure
        terraform fmt -check $(find . -name '*tf')

    - name: "INFO: Validate Terraform Configs"
      shell: bash
      run: |
        cd infrastructure
        for d in $(find . -type d -mindepth 1 -maxdepth 1)
        do
          echo "Validating the $d config"
          cd $d
          terraform init -backend=false
          terraform validate
          cd ..
        done
