---
name: "Terraform Checks"
description: "Perform common Terraform checks"
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Cache plugin dir
      uses: actions/cache@v4
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashFiles('.tflint.hcl') }}

    - name: "INFO: Setup TFLint"
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.52.0

    - name: "INFO: Print version of tflint"
      shell: bash
      run: tflint --version

    - name: "INFO:  Init TFLint"
      shell: bash
      run: tflint --init

    - name: "INFO:  Run TFLint"
      shell: bash
      run: tflint -f compact

    - name: "INFO: Ascertain Terraform Version"
      shell: bash
      run: terraform --version

    - name: "INFO: Linting Terraform Files"
      shell: bash
      run: |
        cd infrastructure
        terraform fmt -check $(find . -name '*tf')

    - name: "INFO: Checking Terraform Format of Files"
      shell: bash
      run: |
        cd infrastructure
        terraform fmt -check $(find . -name '*tf')

    - name: "INFO: Validate Terraform Configs"
      shell: bash
      run: |
        cd infrastructure
        for d in $(find . -type d -mindepth 1 -maxdepth 1)
        do
          echo "Validating the $d config"
          cd $d
          terraform init -backend=false
          terraform validate
          cd ..
        done
