---
name: "Terraform Checks"
description: "Perform common Terraform checks"
inputs:
  terraform_base_dir:
    description: Which base dir to search for the Terraform config(s) in
    required: false
    default: infrastructure
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Check for .tflint.hcl file
      shell: bash
      run: |
        if [ -f .tflint.hcl ]; then
          echo "INFO: .tflint.hcl file found in the root directory."
        else
          echo "ERROR: .tflint.hcl file is missing. Please add it to the root of the repository. See the internal terraform docs"
          exit 1
        fi

    - name: Cache plugin dir
      uses: actions/cache@v4
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashFiles('.tflint.hcl') }}

    - name: "Setup TFLint"
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.53.0

    - name: "Print version of tflint"
      shell: bash
      run: tflint --version

    - name: "Init TFLint"
      shell: bash
      run: tflint --init

    - name: "Run TFLint"
      shell: bash
      run: tflint --chdir ${{ inputs.terraform_base_dir }}/ --recursive

    - name: "Ascertain Terraform Version"
      shell: bash
      run: terraform --version

    - name: "Checking Terraform Format of Files"
      shell: bash
      run: |
        cd ${{ inputs.terraform_base_dir }}
        terraform fmt -check $(find . -name '*tf')

    - name: "Validate Terraform Configs"
      shell: bash
      run: |
        cd ${{ inputs.terraform_base_dir }}
        for d in $(find . -type d -mindepth 1 -maxdepth 1)
        do
          echo "Validating the $d config"
          cd $d
          terraform init -backend=false
          terraform validate
          cd ..
        done
