name: Terraform Check - With Defined Version

on: [push, pull_request]

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Run Terraform Checks Action from oak-terraform-actions
        uses: oaknational/oak-terraform-actions/actions/terraform-checks@main
        with:
          terraform_version: 1.5.7 # or any other version as needed
