---
name: YAML Syntax Check

on: [push, pull_request] # yamllint disable-line rule:truthy

jobs:
  lint-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: "Install yamllint"
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: "Run yamllint"
        run: yamllint .
